
name: Meterian Scanner workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        container:
          image: meterian/cli:2.3.69-gha
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Meterian Scanner
            env:
              METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
              GITHUB_TOKEN: ${{ github.token }}
              INPUT_AUTOFIX_SECURITY: aggressive
              INPUT_AUTOFIX_STABILITY: safe
              INPUT_AUTOFIX_WITH_ISSUE: true
              PRE_SCAN_SCRIPT: scripts/test.sh
            run: meterian_github_action.sh v1.0.13
